version: "3.8"

services:
  omniuserbot:
    build: .
    container_name: omni_userbot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./downloads:/app/downloads
      - ./omni_userbot.session:/app/omni_userbot.session
